### ISSUE TITLE
Configurable WnckWindowType filter

### ISSUE THREAD

**Issue by Frenzie** [XCMer/fuzzy-window-switcher#10]
I'm thinking you should at the very least also filter out the Wnck.WindowType.DESKTOP type by default, but ultimately people's preferences are probably all over the place. Or perhaps it makes more sense to white-list instead.

For example, WNCK_WINDOW_UTILITY, WNCK_WINDOW_MENU, and WNCK_WINDOW_SPLASHSCREEN are all part of e.g. GIMP. But I typically just want to switch to the GIMP main window.

So anyway, most people would probably only want to show NORMAL and DIALOG by default.

**Comment by XCMer** [comment]
I'm thinking of adding a whitelist/blacklist system. This will allow you to, say, hide all the docks but one (and things like that). Then, there'd be a blacklist for window types as well. Finally, the window titles that you'd specify would support regex, which can come in handy. Let's see how this goes.

**Comment by Frenzie** [comment]
That'd be awesome.

**Comment by XCMer** [comment]
I've implemented this. It works as follows:

You can now specify an `always_show_windows` option (just like the `ignored_windows`) option, separated by newlines. Both the options are regex enabled. The windows that match any of the regexes in `always_show_windows` will always be shown, regardless of opposing matches in the `ignored_windows` list or the ignored window type list.

For the window types, you can now specify which window types to show. By default, all of them show. The syntax for them in the config file is as follows:

```
show_windows_normal=1
show_windows_desktop=1
show_windows_dock=1
show_windows_dialog=1
show_windows_toolbar=1
show_windows_menu=1
show_windows_utility=1
show_windows_splashscreen=1
```

Turn any of them to 0 and that window type won't be shown.

**Comment by Frenzie** [comment]
That's good stuff.

**Comment by XCMer** [comment]
Great! Now all that remains is to document these changes properly.
