### ISSUE TITLE
Document key names used in config

### ISSUE THREAD

**Issue by dpashkevich** [XCMer/fuzzy-window-switcher#14]
Perhaps a list of key constants that can be used in `hotkey` config value would be useful. I can't figure out how to set <kbd>Scroll Lock</kbd> as hotkey.

**Comment by XCMer** [comment]
I'll update the wiki soon with detailed information on all the available key combinations.

**Comment by Frenzie** [comment]
Scroll_Lock does the trick for me. I think `xev` is probably the easiest means of getting the relevant keysyms.

**Comment by dpashkevich** [comment]
Thanks for the tip!

**Comment by Frenzie** [comment]
Btw, is there a GitHub Markdown means of getting <kbd>key</kbd> or did you just type the HTML?

**Comment by dpashkevich** [comment]
gh markdown supports the HTML `<kbd>ESC</kbd>`
