### ISSUE TITLE
Desktop window not ignored by default

### ISSUE THREAD

**Issue by dpashkevich** [XCMer/fuzzy-window-switcher#15]
The doc says:

> Certain windows are ignored and not shown to you, because they're common system specific ones. **The default ones ignored are**: 'XdndCollectionWindowImp', 'unity-launcher', **'Desktop'**, 'unity-panel', 'unity-dash', 'Hud', 'Guake!'

However, I see `Desktop` in the window list. I manually added it to `ignored_windows` in my config and now it's gone.

**Comment by dpashkevich** [comment]
Notice that it happens regardless of whether the file `~/.fuzzy-windows` exists or not.

**Comment by XCMer** [comment]
Sorry for that. I've yet to update the README with the new details. Currently, there is a support for ignoring window types, and window titles via regex. For this reason, I've removed any default ignoring that's happening. I'll probably update this in the Wiki and reference it from the README.

**Comment by dpashkevich** [comment]
Oh, ok, sorry for racing ahead, thanks for creating this wonderful script btw!

**Comment by XCMer** [comment]
I've written and included the updated documentation in the docs folder. It should explain the added functionalities.
