### ISSUE TITLE
Hiding header and accidentally quitting (basic ideas, not sure where I should post this)

### ISSUE THREAD

**Issue by lodmfjord** [XCMer/fuzzy-window-switcher#16]
i'm kind of bored with the header so I edited fuzzy-windows and put this line:
Gtk.TreeView.set_headers_visible(self.appListView, False)        

just before  "Create the necessary columns"

I also disliked that fuzzy-windows had decorations, because I tend to accidentally close the window and thus quitting the program. I added this line:
Gtk.Window.set_decorated(self,False)

after:
Gtk.Window.**init**(self, title='Fuzzy Windows')

**Comment by XCMer** [comment]
I think someone had recommended removing the TreeView headers. And I agree with that. I had tested removing the window decorations. However, I'll need to find a way by which the user can quit the application as well.

**Comment by Frenzie** [comment]
Alt+F4 works fine for me, but that might be my WM? You could add e.g. Ctrl+Q; that's fairly standard I'd say.

**Comment by XCMer** [comment]
I believe Alt+F4 is pretty standard. However, I will still add an alternate binding, and maybe make it configurable.

**Comment by XCMer** [comment]
All decorations removed with `Alt+F4` being used to quit for now.
