### ISSUE TITLE
Add a way to directly go to a window with [0-9], [a-z], and [A-Z].

### ISSUE THREAD

**Issue by Frenzie** [XCMer/fuzzy-window-switcher#2]
I realize this is a _fuzzy_ window switcher, but to me the best Alt-Tab replacements I ever used is http://smarttab.org/

It numbers all the windows so you can go straight to them. 

The way it works is you press Alt+Tab to activate the switcher, hold Alt, and then press the number or letter of the window to which you wish to switch. (Should I add a separate issue for actually replacing Alt+Tab or are you not interested in this kind of direction?)

**Comment by XCMer** [comment]
This is a good suggestion. However, I'm thinking about a case wherein we have a large number of windows. There are limited number of window titles that we can show on the screen. So, we don't be able to see the numbers/letters for them. Any ideas?

**Comment by Frenzie** [comment]
I'm not entirely sure what to do if there are truly too many, but if it's just too many to fit in a single list then I think you should expand sideways instead of scroll. This is the solution used by the start menu in Windows 98, which I think is much better than the scrolling as in later versions of Windows and GNOME. If it still doesn't fit, I suppose the most obvious solution is e.g. pressing Pg Dn or the down arrow key.

Since even on lowly netbook resolutions you'd probably need over 50 windows open to actually reach this kind of scenario, I'm not sure if it's really that big of a problem? After all, I only suggested a total number of 61 direct shortcuts, which is the same problem in another guise. Although I actually have some proposals for how to work around that problem. :)

**Comment by XCMer** [comment]
Actually, it would be a problem if there are too many windows. The fuzzy match allows you to instantly bring relevant windows to the top. However, an order might not be implied with a purely numerical approach. You would have to search through all the open windows to find the number corresponding to your particular window (and then open it using the shortcut). It'd be relatively faster to, say, dock your most used applications on Unity's Launcher and click on the relevant one.

However, this does give me an idea to open the first 5 or so windows with a shortcut. After typing something, there is a good possibility that your intended window might be in the top 5, but not the topmost. So, a shortcut can come in handy in this case. Right now, you manually have to use the mouse to select a window not on the top. I'll brainstorm this a bit.

**Comment by Frenzie** [comment]
Last year I wrote down some thoughts on this general topic: http://fransdejonge.com/2012/08/musings-on-window-switching/ It was kind of a train of thought piece of writing, so it might not be the clearest. Besides, you no doubt you have very different thoughts.

I thought you'd most likely disagree with making fuzzy window switching a "mere" secondary means of switching windows; you wrote a fuzzy window switcher after all! ;) But in my ideal window switcher you'd have the list of [0-9] followed by [a-z], and you'd press e.g. : for fuzzy switching. Another idea is to press e.g. # to give _all_ the windows a number if the 61 suggested shortcuts don't suffice. Since you wrote this in Python rather than C I might actually be able to fork this and do it myself when I find some time, so thanks an awful lot regardless what you decide.

Anyhoo, I recommend you compile [https://code.google.com/p/superswitcher/](superswitcher) from SVN for some inspiring work. Its workspace switching/management and direct closing with Esc are pretty neat features. And if you have Windows XP around, I'd also recommend you check out SmartTab.org, because to my mind, only those two and what you're writing right now have contributed anything worthwhile to window switching since Windows 3. (Excluding anything I'm not familiar with, obviously.)

**Comment by XCMer** [comment]
I do understand your point. For example, the EasyMotion plugin for Vim does something very similar, and it is extremely powerful.

When it comes to selecting windows by assigning them numbers (then letters, then multiple letters), it is essential to see the entire window list at once. Right now, Fuzzy Windows hardly shows a few.

I'm visualizing something like the "Keyboard Shortcuts" window that pops up when you hold down the super key in  unity. In that case, we could easily accommodate a lot of windows clearly, and also show their respective numbers. Additional things would be grouping applications of the same window.

This is also a great way of switching windows, but it would most likely have to be a separate project. I'll start drawing up some sketches and dig up some technical stuff related to this.
