### ISSUE TITLE
Numbered windows for faster switching (feature request)

### ISSUE THREAD

**Issue by sanchitbh** [XCMer/fuzzy-window-switcher#32]
I was wondering if we can add a number to the left of each window so that instead of using arrow keys we can just type the number (like 1, 2, 3) to switch to that window?

Thanks!

**Comment by Frenzie** [comment]
That's a duplicate of #2. The response was as follows:

> This is also a great way of switching windows, but it would most likely have to be a separate project.

As such, I wrote my own fork that does just that: https://github.com/Frenzie/nimbler

You might also be interested in the similar software section I added to the docs [here](https://github.com/Frenzie/nimbler/blob/master/docs/docs.md#similar-software). I'll quote it for simplicity.

> ## Similar Software
>If you're reading this, you're probably interested in other alternatives to the default application switchers. In no particular order, here are a few that might be of interest:
>
>* [fuzzy-window-switcher](https://github.com/XCMer/fuzzy-window-switcher) is Nimbler's parent and it does what the name implies.
>* [superswitcher](http://code.google.com/p/superswitcher/) is quite nice. However, it has been [discontinued](http://blogs.gnome.org/nigeltao/2013/01/28/so-long-and-thanks-for-the-super-switching/).
>	* Because it hasn't been updated in a while, at least two minor forks exist: [smartswitcher](https://github.com/Frenzie/smartswitcher) and [switchy](https://github.com/cmpitg/switchy).
>* [simpleswitcher](https://github.com/seanpringle/simpleswitcher) is a superswitcher fork that is far more similar to fuzzy-window-switcher than to superswitcher, except its matching is not fuzzy.
>* [Rofi](https://davedavenport.github.io/rofi/) is a simpleswitcher fork that adds fuzzy matching, making it even more similar in nature to fuzzy-window-switcher. It also adds some extra features.
>
>Spiritually, the main concept behind Nimbler itself is based on the Windows program [SmartTab.org](http://smarttab.org/).

I've currently got Super (Win)+backtick bound to nimbler and Alt+backtick to Fuzzy Window Switcher. That's actually kept me from properly adding the fuzzy selection part to nimbler though (still there in the backend of course), because I actually disagree that they're two separate projects. ;-) The colon (`:`) has a special function to trigger to fuzzy matching mode. But like I said, that's just planned for sometime in the future. :-D

**Comment by sanchitbh** [comment]
ok, great.. thanks for the reply. I just tried nimbler and it's great. Unfortunately I have the same problem with Nimbler that I'm having with fuzzy-windows too. The app gets raised but it does not get the focus, i.e. it comes to foreground but if I type something it still gets typed in the last focused window. 

Running NAME="Linux Mint", VERSION="18.2 (Sonya)" if that matters. I also tried simpleswitcher and rofi too and they don't have this problem.

**Comment by Frenzie** [comment]
It might be related to a window manager focus setting. I assume that Cinnamon has a configuration dialog similar to this one from Xfce:
![screenshot_2017-10-17_10-24-56](https://user-images.githubusercontent.com/202757/31654190-84c0ff8a-b325-11e7-81c6-b1486e285863.png)

It looks like simpleswitcher basically [steals the keyboard](https://github.com/seanpringle/simpleswitcher/blob/cbc89a71a61fd2d164c3fdc3ef4d3fa809c1741a/simpleswitcher.c#L370-L384) (which I think is simply the way superswitcher did it).

You could investigate whether swapping or duplicating some of the focus grabbing makes a difference, though I doubt it:

https://github.com/XCMer/fuzzy-window-switcher/blob/3359a5002f53324d1b7cded05594874e60aa9490/fuzzy-windows#L227-L240

More likely to help, there might be some other relevant window methods we could try:
http://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Window.html

**Comment by sanchitbh** [comment]
There is a setting for "Prevent focus stealing" but that was already disabled. Thanks for suggesting `Rof`, it is working very nicely for me. Thanks again for the help!

**Comment by Frenzie** [comment]
Rofi doesn't support one-key switching, does it? That's the entire reason I adapted Fuzzy Window Switcher into what I dubbed Nimbler, not just for the heck of it.[1] :-P (Although of course Rofi didn't exist as more than an early simpleswitcher fork back in 2014).

[1] Perhaps that's not entirely true. I was curious about the Python GTK bindings. They're pretty neat.

**Comment by sanchitbh** [comment]
No, it doesn't and that's a really killer feature of Nimbler (also why i created this thread). Also I think Nimbler has thumbnails or icons (?) which makes it more to my liking. I would switch to it in a heartbeat if I could figure out a way to get the focus thing to working. Not very knowledgeable about python or C, but I plan spend sometime on it.
