### ISSUE TITLE
Issues with Keybinder 3 on Debian Testing

### ISSUE THREAD

**Issue by weatheredwatcher** [XCMer/fuzzy-window-switcher#6]
I am running Debian testing and I get the following error:

```
Traceback (most recent call last):
  File "./fuzzy-windows", line 4, in <module>
    gi.require_version('Keybinder', '3.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 77, in require_version
    (namespace, version))
ValueError: Namespace Keybinder not available for version 3.0
```

I have Keybinder 3 installed.  I'll keep at it and keep this thread updated if I find a solution.  Any suggestions would be appreciated.

**Comment by Frenzie** [comment]
keybinder-0.3.0 is not the same thing as keybinder-3.0. The former works with GTK2, while the latter is for GTK3.

What I wrote in #4 should probably also work in Jessie.

PS This seems to be the relevant bug report http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=698638

**Comment by weatheredwatcher** [comment]
I was wondering about that!  It wasn't very clear in the repo.  I'll give your suggestions in the wiki a try...it should work just fine.

**Comment by XCMer** [comment]
Let me know if it worked out. I'll close this issue if it did.
