### ISSUE TITLE
How to set Ctrl+key as hotkey ?

### ISSUE THREAD

**Issue by MrJJJ** [XCMer/fuzzy-window-switcher#7]
Is it possible and if yes what is the correct syntax in .fuzzy-windows.
Great app by the way.

**Comment by XCMer** [comment]
This should work in your config:

```
[DEFAULT]
hotkey=<Ctrl>w
```

The above sets `Ctrl+w` to be the hotkey.

**Comment by MrJJJ** [comment]
Great thanks. What about Alt ? I tried <Alt> and <Meta> but it doesn't work.

**Comment by XCMer** [comment]
It seems that keybinder fails when you directly try to bind the Alt key. However, something like `<Ctrl><Alt>d` works. I've also released an update that quits the application if the key could not be bound, so that you don't have to manually kill the process.

**Comment by Frenzie** [comment]
It works for me with Alt, although I can't figure out how to do e.g. 

```
<Alt>`
```
