### ISSUE TITLE
Use ~/.config/fuzzy-windows

### ISSUE THREAD

**Issue by Frenzie** [XCMer/fuzzy-window-switcher#8]
I prefer it when configuration files aren't all over `$HOME`.

The de facto standard seems to be a directory like `~/.config/fuzzy-windows/`. Inside the folder, Xfce apps converge on `fuzzy-windowsrc`, but e.g. Deadbeef merely uses `config`, while qBittorrent and Synergy use `fuzzy-windows.conf`.

**Comment by XCMer** [comment]
Yes, this makes sense. I'll implement this shortly. I'll have it so that it searches both the home directory and the .config folder.

**Comment by Frenzie** [comment]
Btw, for syntax highlighting I think fuzzy-windows.conf might be the better choice.

**Comment by XCMer** [comment]
The config file is now searched for in four locations: `~/.config/fuzzy-windows.conf`, `~/.config/.fuzzy-windows`, `~/fuzzy-windows.conf`, `~/.fuzzy-windows`.
