### ISSUE TITLE
Use WnckWindowType

### ISSUE THREAD

**Issue by Frenzie** [XCMer/fuzzy-window-switcher#9]
Here's a quick non-working sample that should give you the right idea, but since I don't know Python unfortunately I'm not sure what I'm doing wrong. It's probably not a string or something.

```
        for i in window_list:
            # Filter out extraneous windows
            name = i.get_name()
            type = i.get_window_type()
            if name in self.ignored_windows:
                continue
            #print type
            if type == 'WNCK_WINDOW_DOCK':
                continue
            self.windowList.append({'name': name, 'icon': i.get_icon(), 'window': i, 'rank': 0})
```

Here's the docs:
https://developer.gnome.org/libwnck/stable/WnckWindow.html#WnckWindowType

This kind of thing should be much more efficient than adding xfce4-panel and all those other panels to the ignore list.

**Comment by Frenzie** [comment]
On a semi-related note, would you consider using tabs instead of spaces?

**Comment by XCMer** [comment]
I used your suggestion. Now, all the docks are ignored and the ignore list is blank by default. You can check out the right syntax in the updated file in the repository.

For now, I'll keep the indents at 4 spaces. I don't have a particular reason for using spaces, but that's what I've been doing all along. The usage of tabs is equally valid.

**Comment by Frenzie** [comment]
a7ca891f019994d73522985e98b5fea3af44540c For my own benefit, this is the relevant commit.
